1.1.5更新内容
AirtestProject/Airtest pull request #802
Opened 2020-09-16 08:54 UTC by yimelia

重要的修改项如下：

1. ios修复了上个版本stopapp失效的问题 https://github.com/AirtestProject/Airtest/commit/6bf146becc56b2737288941d0771b013d183bc96

2. `log()`接口增加了两个参数，目前4个参数为`arg, trace="", timestamp=None, desc=""`，（https://github.com/AirtestProject/Airtest/commit/777b5ffe51cfc41c7c05b3bcf289edc38f861774， https://github.com/AirtestProject/Airtest/commit/77a4893be37bb7a3094171af27993fb6b593a0c1 ）
- `args` 可以是字符串或是traceback对象，现在还支持传入非字符串，并且对py2做了一下兼容
- `trace` 可以传入一个traceback对象
- `timestamp`参数可以自定义当前这条log的时间戳（记录一些长时间的回调中获取到的log时，原本默认是记录写入log的时间，但是可能需要修改为log产生的时间）
- `desc` log显示的时候自定义一个标题，在报告中更好看
调用示例： **感觉参数还是太多了，待合并**
```
data = {"test": 123, "time": 123456}
log(data, timestamp=time.time(), desc="log标题")
try:
    1/0
except Exception as e:
    log(e)
log("中文")
```

3. 回退了屏幕录制代码到1.0.27之前的版本，取消使用yosemite.apk来录屏，避免重装过yosemite后必须要手工赋予录屏权限才能录屏的问题 https://github.com/AirtestProject/Airtest/commit/12221aa60338ec5c4f2ae8d91249216e98e6e9dd

4. 在一些无法使用minicap的手机上，虽然指定了Javacap模式也能截屏，但是会在get_display_info的时候依然调用到minicap，必须强制指定ori_method为adbori才行。这样会导致多一步操作，大部分用户会卡在这里无法进行正常流程，因此改为假如`get_display_info`默认的minicap方式失败时，就改为调用adbori  https://github.com/AirtestProject/Airtest/commit/9312f0d52a6dbf28a9b84ed51e338686d68ed875

5. 有些手机假如运行了不止一次connect_device，并指定了不同的设备连接参数时，`G.DEVICE`不会更新到最新参数创建出来的设备对象，现在改为每次更新设备对象时，也会自动更新一下`G.DEVICE` https://github.com/AirtestProject/Airtest/commit/c163a4f46b95c9ad758fa666cf113696bbe7ce6d

6. 修复了几个截图质量参数设置后不生效的问题， https://github.com/AirtestProject/Airtest/commit/31e40122e723a36cc23e13716a48d336069a73ea：
- `snapshot`接口支持传入`quality`参数，单独指定本次截图的图像精度
- 目前可以使用`ST.SNAPSHOT_QUALITY = xx` 设置全局截图精度，在运行脚本时，报告的步骤截图也会采用这个数值进行压缩

2020-09-20 05:32 UTC, Meteorix requested changes

2020-09-20 05:32 UTC, Meteorix commented on airtest/core/android/android.py
> +        try:
这个if /try/ return 有点乱，重写一下吧

2020-09-20 05:32 UTC, Meteorix commented on airtest/core/api.py
> +        try:
这里没必要容错吧，直接抛出来更好

2020-09-20 06:49 UTC, yimelia commented on airtest/core/android/android.py
> +        try:
改成这样看看会不会好点？
```
if self.ori_method == ORI_METHOD.MINICAP:
    try:
        return self.minicap.get_display_info()
    except RuntimeError:
        return self.adb.get_display_info()
return self.adb.get_display_info()
```

2020-09-24 03:58 UTC, yimelia commented on airtest/core/android/android.py
> +        try:
这个改完提交了，可以再看看

2020-10-10 05:02 UTC, Meteorix approved these changes

2020-10-10 07:13 UTC, merged