1.1.8
AirtestProject/Airtest pull request #860
Opened 2021-02-03 03:38 UTC by yimelia

BUG FIX:

1. 如果minicap没有成功启动、或是RotationWatcher.apk没安装成功，就换用adb获取ori信息，新增了使用ADB线程不断获取ori信息的逻辑 https://github.com/AirtestProject/Airtest/commit/1b85fc7c26813e0b6c429cadb48adef5362943ed
2. 如果ori_method运行失败、Yosemite.apk安装失败（如果已经安装过旧版，允许跳过安装），也能保证基础功能的运行 https://github.com/AirtestProject/Airtest/commit/b1c8568792bd710674a64c6a45b0566dafde1a60 https://github.com/AirtestProject/Airtest/commit/f1f095c10fbe2c2f03872a730cbae36c5b8dc986
3. 修复上个版本引入的问题，py2下不能正常截图 https://github.com/AirtestProject/Airtest/commit/a6e8f68fdd14e318f0908c3c995b5d3c384167ac

重大更新：

ios模块全面弃用旧的wda文件，改用[facebook-wda](https://github.com/openatx/facebook-wda)最新版本，好处有：
- 能支持Appium的WDA，比ios-Tagent兼容性更好，能支持最新的xcode和ios版本
- 增加了一些新接口和新功能，最重要的是可以点击弹窗了
- 代码能够更加简化

因此删除了airtest/core/ios文件夹下的wda相关文件，只保留airtest接口，并且全面重新进行了迭代，主要改动如下：
- 所有的接口换用新的wda接口
- ios所有接口全部用同一个session点击，避免了同时有多个进程在连接ios时会导致session不断被重置的问题
- 虽然现在session重置的问题基本已经避免了，但是还是为每一个接口都增加了一个重新获取session的装饰器，一旦接口运行失败，就尝试重新获取一下，避免脚本运行失败
- 去掉或者修改掉了旧版ios.py里不合理的逻辑，例如在每一次snapshot的时候都会重复计算一遍当前的画面尺寸和点击比例参数，以及在每一次点击都需要去判断一遍当前是不是home界面、是不是横屏的逻辑
- 在一些特殊尺寸屏幕的设备上（例如ipad，以及6P/7P/8P），在HOME界面并且横屏或者颠倒屏幕的情况下，点击坐标需要额外进行一次转换，否则的话都按正常坐标传给WDA点击即可。
  - 这个实际上是WDA的一个BUG，我们之前每一次点击都做一次判断，导致点击速度更慢了
  - 现在改为在初始化的时候会事先判断好是否是特殊设备（用是否ipad，以及屏幕尺寸是否符合几款Plus手机来判断，暂时没找到更好的判断逻辑）
  - 如果不是特殊设备，就直接点击对应坐标，如果是特殊设备，需要针对当前的屏幕旋转方向，做一次坐标转换，将坐标转成竖屏坐标再传入
- 重要：由于`facebook-wda`只支持py3，因此假如想升级到这个版本使用ios模块，必须使用python3

涉及到的文件：
- `ios/constant.py`
- `ios/ios.py`
- `ios/rotation.py`
- `tests/test_ios.py`

2021-02-07 13:56 UTC, Meteorix requested changes

2021-02-07 13:56 UTC, Meteorix commented on airtest/core/helper.py
> +        try:
这里不用try catch，直接判断

2021-02-07 13:56 UTC, Meteorix commented on airtest/core/android/android.py
> +                LOGGING.error("RotationWatcher.apk update failed, please try to reinstall manually.")
这里真的要这样容错吗？是不是直接抛出来更好？

2021-02-07 13:56 UTC, Meteorix commented on airtest/core/android/yosemite.py
> +                LOGGING.error("Yosemite.apk update failed, please try to reinstall manually.")
同样

2021-02-07 14:08 UTC, yimelia commented on airtest/core/android/android.py
> +                LOGGING.error("RotationWatcher.apk update failed, please try to reinstall manually.")
因为新实现了一个线程直接用纯adb方式读取当前设备方向的方法，在RotationWatcher.apk安装失败的设备上（例如一些特殊的安卓平板、安卓智能设备），也能用备用方案运行起来。以及现在只要有任何一个apk不能安装成功，airtest就会直接中断不能跑，导致失败率很高（只要设备禁止安装apk、或是不能装、或者用户不知道要手动点同意，整个流程就会直接断掉，后面要经过很长时间的查文档或者问人才能继续推进流程，或者干脆直接在这一步就流失掉了），但是实际上大部分操作都可以不依赖这些apk的，因此这个版本增加了一定程度上的容错

2021-02-07 14:10 UTC, yimelia commented on airtest/core/helper.py
> +        try:
这里try的原因是，py2下面会因为import wda失败而导致跑不起来，但是报错信息里不会明确说出错误原因是因为本地环境是python2（而会报wda.XXXX变量import失败，因为wda整个库都不能被import），因此增加了python2升级的提示信息，避免用户感到迷惑

2021-02-07 14:44 UTC, Meteorix requested changes

2021-02-07 14:44 UTC, Meteorix commented on airtest/core/helper.py
> +        try:
就是在这里判断py2，用if else，而不需要try catch

2021-02-07 14:44 UTC, Meteorix commented on airtest/core/android/android.py
> +                LOGGING.error("RotationWatcher.apk update failed, please try to reinstall manually.")
那这里改成user warning吧，提示用户手动重装

2021-02-08 03:08 UTC, yimelia commented on airtest/core/android/android.py
> +                LOGGING.error("RotationWatcher.apk update failed, please try to reinstall manually.")
重新改为在`ios/__init__.py`里面判断，能覆盖到更多情况：https://github.com/AirtestProject/Airtest/pull/860/commits/04cc5665517f21d4a4b2aebacc5ff301d2aad59e

2021-02-08 03:08 UTC, yimelia commented on airtest/core/helper.py
> +        try:
重新改为在`ios/__init__.py`里面判断，能覆盖到更多情况：https://github.com/AirtestProject/Airtest/pull/860/commits/04cc5665517f21d4a4b2aebacc5ff301d2aad59e

2021-02-08 03:12 UTC, yimelia commented on airtest/core/android/yosemite.py
> +                LOGGING.error("Yosemite.apk update failed, please try to reinstall manually.")
这里和RotationWatcher.apk有一点点不同，Yosemite.apk有时候会有一些小版本更新，但是一般改动不会太大，如果每次升级Yosemite.apk之后都强制重装新版本，会导致一旦更新都要重新给所有的手机点一遍安装弹窗，会造成很多额外的手工操作、也容易引起用户抵触更新。因此改为假如新版本安装不成功，但是又能检测到老版本yosemite.apk的话，就允许跳过本次安装，继续跑后面的流程，这样至少能保障大部分手机能跑脚本，如果有使用新版本yosemite.apk的用户就再额外注意升级apk就行了。

此处也改为user warning

2021-02-08 03:17 UTC, Meteorix approved these changes

2021-02-08 03:33 UTC, merged